#!/bin/sh

dir=$(pwd)
echo "Installing todocli..."
if [ -d "/usr/lib/todocli" ]; then
    cp $dir/*.py /usr/lib/todocli/
    cp $dir/todocli /usr/lib/todocli/
else
    mkdir /usr/lib/todocli; cp $dir/*.py /usr/lib/todocli/
    cp $dir/todocli /usr/lib/todocli/
fi
cd /usr/lib/todocli
rm -rf .git
rm config-example.py 
cp $dir/.run/todocli /usr/bin
